### ISSUE TITLE
No augtexnames.txt file

### ISSUE THREAD

**Issue by Enuvesta** [cvlab-stonybrook/DewarpNet#1]
Hi!
For training WC flag augmentations=True is passed in dataloater
https://github.com/cvlab-stonybrook/DewarpNet/blob/bdf01e613792f940c6ec45c4e3ebc5789b1703c6/trainwc.py#L40

So, there is augtexnames.txt file:
https://github.com/cvlab-stonybrook/DewarpNet/blob/bdf01e613792f940c6ec45c4e3ebc5789b1703c6/loaders/doc3dwc_loader.py#L41

I couldn't find it in repository. How should this file look like?

Thanks~

**Comment by SugarMasuo** [comment]
Hello @Enuvesta , did you review the code of models, do you understand the dense block implemented here? Look forward to your reply! Thank you!

**Comment by Enuvesta** [comment]
Hi @SugarMasuo! As to me, this is kind of a special implementation of dense block. Due to Fibonacci-like computation this net is called densenet-style and not straight densenet.
Bat I am waiting for the reply of the author as you are.

**Comment by SugarMasuo** [comment]
can you train this network with its dataloader? One GPUhas much higher video storage than the other two, and the speed of dataloader is low, I don't know whether I use it in a wrong way. Do you have the same problem?

**Comment by SugarMasuo** [comment]
> Hi @SugarMasuo! As to me, this is kind of a special implementation of dense block. Due to Fibonacci-like computation this net is called densenet-style and not straight densenet.
> Bat I am waiting for the reply of the author as you are.

can you share your email? I think we can talk about these problems together! You can see my email at my  homepage.

**Comment by Enuvesta** [comment]
@SugarMasuo it is sugarmasuo@gmail.com?

**Comment by sagniklp** [comment]
> Hi!
> For training WC flag augmentations=True is passed in dataloater
> https://github.com/cvlab-stonybrook/DewarpNet/blob/bdf01e613792f940c6ec45c4e3ebc5789b1703c6/trainwc.py#L40
> 
> So, there is augtexnames.txt file:
> https://github.com/cvlab-stonybrook/DewarpNet/blob/bdf01e613792f940c6ec45c4e3ebc5789b1703c6/loaders/doc3dwc_loader.py#L41
> 
> I couldn't find it in repository. How should this file look like?
> 
> Thanks~

Sorry, I forgot to attach the file. It should be list of texture paths you will use as background.

**Comment by SugarMasuo** [comment]
> @SugarMasuo it is [sugarmasuo@gmail.com](mailto:sugarmasuo@gmail.com)? I can not see it on your homepage :(

Sorry, it's ok now. tyang_young_1@163.com

**Comment by SugarMasuo** [comment]
> Hi @SugarMasuo! As to me, this is kind of a special implementation of dense block. Due to Fibonacci-like computation this net is called densenet-style and not straight densenet.
> Bat I am waiting for the reply of the author as you are.

Fibonacci-like computation?  I don't understand.
It seems the layer is only applied once. Thus, outputs[-1] will output some scalar * self.layers[0](inputs) and it does not look like a valid dense block. Same problem also occurs in DenseBlockDecoder class.
https://github.com/cvlab-stonybrook/DewarpNet/blob/f91bdf6248789e58c836cee828493d962396ec0c/models/densenetccnl.py#L86-L97

**Comment by Enuvesta** [comment]
@SugarMasuo Oh, yes. Now I see this problem too. It seems like the output value is a recursive sum of the output of the first layer.

**Comment by SugarMasuo** [comment]
> @SugarMasuo Oh, yes. Now I see this problem too. It seems like the output value is a recursive sum of the output of the first layer.

yes, do you have any idea to correct the network?

**Comment by Enuvesta** [comment]
I guess, the simpliest solution is to change `outputs.append(next_output)` to `outputs.append(layer(next_output))`. But let's wait for the answer @sagniklp will provide us with.

P.S.: @SugarMasuo  I've emailed you. Hope to hear from you soon!

**Comment by SugarMasuo** [comment]
Hi Enuvesta:   

     I am researching the principle of nn.Sequential, maybe the author is right. Because I test the infer.py, the result seems right !
We can research it together!


Regards
Karen



At 2019-11-01 20:34:20, "Diana Polonskaya" <notifications@github.com> wrote:


I guess, the simpliest solution is to change outputs.append(next_output) to outputs.append(layer(next_output)). But let's wait for the answer @sagniklp will provide us with.

P.S.: @SugarMasuo I've emailed you. Hope to hear from you soon!

**Comment by Enuvesta** [comment]
The output of infer.py seems right for me too, but I'm not getting the idea of summing the outputs without applying layer, and the principle of nn.Sequential is not so clear for me.

**Comment by sagniklp** [comment]
That is the correct implementation.
