### ISSUE TITLE
about data argumentation

### ISSUE THREAD

**Issue by fh2019ustc** [cvlab-stonybrook/DewarpNet#14]
Hi，Thanks for your released code. I have one questions：

For shape network,  whether the intensity and color of each training image are also randomly jittered. In code, 

![503bc4f91c3981aed685ad933146ecc](https://user-images.githubusercontent.com/50725551/81880577-680a8200-95c0-11ea-994a-f3143ab680d8.png)
![be069f24553b4ffc32bd73434121499](https://user-images.githubusercontent.com/50725551/81880581-693baf00-95c0-11ea-9631-77d906616a32.png)

1. For function color_jitter(im, brightness=0, contrast=0, saturation=0, hue=0): , should we use the parameter "saturation=0, hue=0";
2. Should we use the function change_intensity()， I find you comment out this code.

What is your implementation of these settings in your public model？

**Comment by sagniklp** [comment]
Saturation and hue is important if you have most of the training images with white background. I think I have used 0.2, 0.2 for saturation and hue.

**Comment by sagniklp** [comment]
Also make sure, the images look correct after changing the hue and saturation.

**Comment by fh2019ustc** [comment]
Thank you very much!
