### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by aishmittal** [cvlab-stonybrook/DewarpNet#15]
Hi,
When I click on Unwarp button on demo page nothing happens. I have tried this with multiple images and none of them is getting dewarpped.
![image](https://user-images.githubusercontent.com/11550572/82985134-1971d480-a011-11ea-82c1-aaad1a16ee6c.png)

**Comment by sagniklp** [comment]
The demo is offline due to the unavailability of GPU resources. Please use the inference code available in the dewarpnet repository.

**Comment by liizhou-888** [comment]
Hi,
I have the same problem. Have you solved your problem and how does the interface code using the repository work?Looking forward to your reply
