### ISSUE TITLE
Question about data acquisition

### ISSUE THREAD

**Issue by sureJson** [cvlab-stonybrook/DewarpNet#18]
Thank you for your nice work! :)

I'm interested in the proposed manner for mesh acqusition and now I follow some steps in your paper.

Is the pin relief system fully automated? (e.g. motor-controlled system)
and how to fix the document to the pin system?
Is the deformation of paper only controlled by the pins?

**Comment by sagniklp** [comment]
Nothing is automated. We fold and put the paper on the pin-relief system and manually adjust the pins to hold the paper.
