### ISSUE TITLE
question about joint training

### ISSUE THREAD

**Issue by fh2019ustc** [cvlab-stonybrook/DewarpNet#19]
Hi, I find that the output world coordinate is resized to (128, 128) frim (256, 256). 
So for joint learning, which size should the supervision put on, the size (256, 256) or (128, 128)?

Thank you!

**Comment by sagniklp** [comment]
We had applied WC loss on 256, BM loss on 128.

**Comment by Chenly1993** [comment]
during joint trainning, the begin losses of the two model are  larger than the separate training. joint training for some epoches, the loss is decreasing. but it is still larger than the separate training. Can you give me some suggestions about joint   training?

**Comment by Wanwan1996** [comment]
> during joint trainning, the begin losses of the two model are larger than the separate training. joint training for some epoches, the loss is decreasing. but it is still larger than the separate training. Can you give me some suggestions about joint training?

**Comment by sagniklp** [comment]
It will be larger than separate training because the input to the bm network is now the predicted wc maps, not the gt wc maps.
Don't worry about it. 
Keep separate optimizers and schedulers for the bm and wc model.
