### ISSUE TITLE
Input and loss function of texture mapping network

### ISSUE THREAD

**Issue by SugarMasuo** [cvlab-stonybrook/DewarpNet#2]
Good job and thank you for sharing! 
Q1:
Besides of wc and bm, the third input of texture mapping is recon or alb? Why this folder is nested in different locations
https://github.com/cvlab-stonybrook/DewarpNet/blob/f91bdf6248789e58c836cee828493d962396ec0c/loaders/doc3dbmnoimgc_loader.py#L53
According to the folder name, recon image is
![image](https://user-images.githubusercontent.com/15923907/67821409-d3df3e80-faf7-11e9-8f74-e9070fec2588.png)
but alb image is 
![image](https://user-images.githubusercontent.com/15923907/67821423-e194c400-faf7-11e9-8d17-aebf53f376d2.png)

Q2:
ssim loss is calculated but isn't brought into training,  is this choose of experimental comparison?
Forward to your replying! Thanks.

**Comment by sagniklp** [comment]
Input is recon not alb.
SSIM is used for comparison.

**Comment by SugarMasuo** [comment]
That's ok.Thank you!
