### ISSUE TITLE
Loss function in refinement network

### ISSUE THREAD

**Issue by naiiytom** [cvlab-stonybrook/DewarpNet#20]
It is stated in the paper that **L1 loss** is used for calculate loss for the _shading estimation network_ but it is not stated that **which loss function** used for _normal estimation network_ part of refinement network.
Could you please tell me?

**Comment by sagniklp** [comment]
I had used L1 and gradient loss but you can also try other losses from relevant literature.

**Comment by naiiytom** [comment]
Thank you
