### ISSUE TITLE
sobel method in grad_loss.py doesn't work

### ISSUE THREAD

**Issue by lxb007981** [cvlab-stonybrook/DewarpNet#21]
https://github.com/cvlab-stonybrook/DewarpNet/blob/dce12ee6bff9938ac371ef9ab45dc3c636a7c4b9/grad_loss.py#L11-L16

Here `ind` is a float object and cannot be interpreted as an integer.

**Comment by Chenly1993** [comment]
Maybe you should use python2

**Comment by lxb007981** [comment]
> Maybe you should use python2

Seems you're right and it works now.:ghost:
