### ISSUE TITLE
About augtexnames.txt

### ISSUE THREAD

**Issue by lifecool** [cvlab-stonybrook/DewarpNet#26]
Good day!
I need to train this, but can not take a train.txt and val.txt for all filenames ...
And how we can get file augtexnames.txt?
Can u upload it here or give the whole examlpe pls)
Thank you!)

**Comment by isNeil** [comment]
same question about augtexnames.txt 
where can I find it / what is in the file?

**Comment by sagniklp** [comment]
It's just the list of DTD file names.

**Comment by Dong-YJ** [comment]
I have the same question about the train.txt 、val.txt、augtexnames.txt，can you show us the example？
Thanks a lot！
