### ISSUE TITLE
dense block

### ISSUE THREAD

**Issue by SugarMasuo** [cvlab-stonybrook/DewarpNet#3]
Hello, I'm confused of the implementation of dense block
https://github.com/cvlab-stonybrook/DewarpNet/blob/f91bdf6248789e58c836cee828493d962396ec0c/models/densenetccnl.py#L62-L66
1、while i >0, even no use the layer
2、do you want use sum instead of torch.cat?

**Comment by sagniklp** [comment]
It is a densenet kind network not exactly densenet. 
Implementation follows from:
https://github.com/zhixinshu/DeformingAutoencoders-pytorch/blob/master/DAENet.py

**Comment by SugarMasuo** [comment]
Thank you for reply! I will check it out.

**Comment by SugarMasuo** [comment]
> It is a densenet kind network not exactly densenet.
> Implementation follows from:
> https://github.com/zhixinshu/DeformingAutoencoders-pytorch/blob/master/DAENet.py

I review the code again, I think I have the same problem with https://github.com/zhixinshu/DeformingAutoencoders-pytorch/issues/8 , use the 'layer' just in the first one?

**Comment by SugarMasuo** [comment]
![image](https://user-images.githubusercontent.com/15923907/68185805-68a4d900-ffdd-11e9-85a8-738efc0fbc48.png)

I debug the forward of this dense block, the final output is just 16*(first layer output), if so why request other 5 nn.Sequential.

**Comment by SugarMasuo** [comment]
If I use forward hook to check, only the first layer is being called
![image](https://user-images.githubusercontent.com/15923907/68262863-73b04580-007f-11ea-9721-c7f5140d4571.png)

**Comment by sagniklp** [comment]
There are infinite ways to build a network. 
This is the exact network that has been used for our Shape Network and you're welcome to use something else. Feel free to change it the way you want. You may or may not get better results.
