### ISSUE TITLE
albedo map file is incomplete

### ISSUE THREAD

**Issue by fh2019ustc** [cvlab-stonybrook/DewarpNet#30]
Hi, thanks for your solid work. 

We download the dataset, but we found that the albedo file only has 8 folders (8/21).

![image](https://user-images.githubusercontent.com/50725551/106220860-5f71de80-6217-11eb-9963-2342b6eedd13.png)

Will the authors public the whole albedo file? 
 
Thanks.

**Comment by sagniklp** [comment]
We use only these albedo files.
