### ISSUE TITLE
Release the rectified images of the refinement network

### ISSUE THREAD

**Issue by fh2019ustc** [cvlab-stonybrook/DewarpNet#32]
Thanks for your solid work!

Could you provide the rectified images of the refinement network or the pre-trained model?
We want to compare the results of our implementation.

Thank you!

**Comment by sagniklp** [comment]
Images are being uploaded here:
https://drive.google.com/drive/folders/14TYoYsYrpvrEzmO7-1Xrk3E6Pm9s5QLv?usp=sharing

Check in a while. Let me know if you have any questions. Thanks!

**Comment by fh2019ustc** [comment]
Thank you! We got the results.
