### ISSUE TITLE
Optimizer in resumption

### ISSUE THREAD

**Issue by anhkhoivh** [cvlab-stonybrook/DewarpNet#43]
Hello, I wonder if the optimizer of the bm model needs to be load from the previous trained model. Because I notice that the wc model does in line 72 of the file trainwc.py ( optimizer.load_state_dict(checkpoint['optimizer_state']) ), while that of file trainbm.py was commented in line 69. Is that a mistake or am I missing something? 
Thank you so much.

**Comment by sagniklp** [comment]
Not required but useful if you continue training from a checkpoint.
