### ISSUE TITLE
Where is a Refinement Network?

### ISSUE THREAD

**Issue by mini102** [cvlab-stonybrook/DewarpNet#45]
Hi, I'm a student studying your project, DewarpNet!
First of all, Thank you for sharing this awesome project :)

I read a paper, and Refinement Network to adjust for illumination effects in the rectified image is obviously recorded in the paper. 
But, I can't find this network in this code.

Is there any training code or pretrained model?

**Comment by mini102** [comment]
Thank you very much for the detailed explanation!

**Comment by mini102** [comment]
Hi, As your explanation, I'm trying to train SE in the refinement network, but I have a problem.
can I make GT shading map (S) by element-wise dividing A from I? (I is unwarped Image by backwardmapping distored original image with flow map(GT of Texture mapping network) , A is unwarped Albedo Image by backwardmapping distored albedo image in doc3d with flow map(GT of Texture mapping network)) 
I understand that way, but still uncertain. 
I'll very happy if you let me know.

**Comment by sagniklp** [comment]
Yes, you get the GT shading maps like that, since I= A*S. Use np.divide to avoid dividing by zero. I will suggest doing the division first then unwarp the shading map using the GT BM. BM is sometimes incorrectly interpolated so you may have erroneous shading values.
