### ISSUE TITLE
Blender camera details

### ISSUE THREAD

**Issue by FloorVerhoeven** [cvlab-stonybrook/DewarpNet#49]
Hi @sagniklp,

I was wondering if you have any details about the camera parameters/model used when rendering doc3D in Blender? Is this constant throughout the dataset or do the camera parameters (other than position & orientation) change?
Do you know the position of the camera in the scene relative to the meshes for each sample from doc3D?

**Comment by sagniklp** [comment]
There are some random parameters; please look into the doc3d-rendering code.
