### ISSUE TITLE
I've completed the form a few days ago, could you please send the username and password to lytao11@163.com? Thanks so much for your work!

### ISSUE THREAD

**Issue by Alxeee** [cvlab-stonybrook/DewarpNet#51]

**Comment by Alxeee** [comment]
I've completed the form a few days ago, could you please send the username and password to lytao11@163.com? Thanks so much for your work!

**Comment by Alxeee** [comment]
I've completed the form a few days ago, could you please send the username and password to lytao11@163.com? Thanks so much for your work!

**Comment by sagniklp** [comment]
We were having data storage issues. It is solved now. I will send the credentials soon. Please try downloading after you receive the uname and passw. Apologies for the inconvenience!
