### ISSUE TITLE
Permission to use as a package

### ISSUE THREAD

**Issue by kobrafarshidi** [cvlab-stonybrook/DewarpNet#53]
Hi,
I'm working on a project that use text in image with extracting OCR machine and your source code is great and can increase accuracy and if I use your source be sure I will consider citing your work.
But the problem is, how can I do that ?
for example How can I write `pip install ...`???
 Best regard,

**Comment by sagniklp** [comment]
We did not release it as a package. You have to download the inference code and use it as a python function.
