### ISSUE TITLE
Questions about doc3dwc_loader

### ISSUE THREAD

**Issue by Aiden0609** [cvlab-stonybrook/DewarpNet#56]
Hi, I've been testing world coordinate loader module, and the output images looks like as if they were completely black, I find there are two normalization process(img / 255 twice), one in "transform" function and the other in "data_aug" function. Is such phenomenon correct? If not, how am I supposed to change it? Thank you.

**Comment by Aiden0609** [comment]
![图片](https://user-images.githubusercontent.com/102793466/236631441-fa57fb34-4ebd-406b-a9ae-666911d079fc.png)

**Comment by sagniklp** [comment]
Yes this is correct!
