### ISSUE TITLE
Model performance 

### ISSUE THREAD

**Issue by SuperYuLu** [cvlab-stonybrook/DewarpNet#6]
Hello, 
Thanks for sharing your code. 

I was able to run the model but it seems doesn't perform as well as illustrated by the paper. 

First, I tried the provided test images under /eval/inp, running with infer.py as suggested by README.md, the output doesn't look as good as those in /eval/uw;

Second, I tested inference with a few photo shots of an article angled on a black background, no other  objects were in the photo. However, the output is either highly twisted or not fully angle-corrected. 

Other info:
Since there is no requirements info provided. I'm running with
pytorch==1.3, CPU only, 
I also replaced numpy.misc.imread function to PIL and fixed dtypes. 

Thank you, 
Julian

**Comment by sagniklp** [comment]
Did you use the model available online?

**Comment by SuperYuLu** [comment]
> Did you use the model available online?
> 
> If you did then try using pytorch 0.4.1. Because the outputs in /eval/uw are generated by running infer.py using the online models.

Thanks for you reply. 

Yes, I downloaded the model from the provided google drive link, then tried:

python infer.py --wc_model_path ./eval/models/unetnc_doc3d.pkl --bm_model_path ./eval/models/dnetccnl_doc3d.pkl --show

The only difference I can see is that I was using pytorch 1.3, maybe I should try it with 0.4.1

**Comment by JasonBoy1** [comment]
> Did you use the model available online?
> If you did then try using pytorch 0.4.1. Because the outputs in /eval/uw are generated by running infer.py using the online models.
> 
> Thanks for your reply.
> Yes, I downloaded the model from the provided google drive link, then tried:
> python infer.py --wc_model_path ./eval/models/unetnc_doc3d.pkl --bm_model_path ./eval/models/dnetccnl_doc3d.pkl --show
> The only difference I can see is that I was using pytorch 1.3, maybe I should try it with 0.4.1

Dear SuperYuLu, I also tried the model with pictures shot by cellphone.I think the robustness is not so good as the example images.

**Comment by sagniklp** [comment]
Make sure the images are tightly cropped.
