### ISSUE TITLE
 folded corners and staples: dataset blind spot?

### ISSUE THREAD

**Issue by drzraf** [cvlab-stonybrook/DewarpNet#61]
I tried this model on a set of A4 photos with very interesting results.
Still, I had multiple items exposing the following defect:
- overzealous crop
- spurious distortion

The condition leading to this are apparently:
- folded corner (or, more exactly partially occlusion of a corner due to another stapled page)
- presence of a staple
- document edge touching the border of the image 
- poor illumination

Details:

- distortion glitch (caused by the mere staple?)
![Screenshot from 2023-11-12 20-58-16](https://github.com/cvlab-stonybrook/DewarpNet/assets/1169926/ce6e4453-fbd9-4e3e-bedd-ab16731cec31)

- another distortion glitch 
![Screenshot from 2023-11-12 20-58-41](https://github.com/cvlab-stonybrook/DewarpNet/assets/1169926/c88db5ab-64e6-4d0f-9379-a67cc687d821)

- overcrop (caused by illumination?)
![Screenshot from 2023-11-12 20-58-55](https://github.com/cvlab-stonybrook/DewarpNet/assets/1169926/5e9569d6-8f8b-489b-bd94-1b4d82b5db43)

- overcrop (caused by the folded edge?)
![Screenshot from 2023-11-12 20-58-47](https://github.com/cvlab-stonybrook/DewarpNet/assets/1169926/b4251480-c8aa-4989-963c-7884f97f24af)

- overcrop + distrortion
![Screenshot from 2023-11-12 20-58-32](https://github.com/cvlab-stonybrook/DewarpNet/assets/1169926/b7dea0ac-b7ce-4788-bc01-f25d53125720)

- overcrop + distrortion
![Screenshot from 2023-11-12 20-58-24](https://github.com/cvlab-stonybrook/DewarpNet/assets/1169926/cb9b0ecd-64ed-4cde-8ac7-43608f4afe92)

- overcrop (document's top border touching the edge of the image?)
![Screenshot from 2023-11-12 20-57-56](https://github.com/cvlab-stonybrook/DewarpNet/assets/1169926/65dd1ce5-0da9-4780-9d1d-cb916300c8c9)

- overcrop
![Screenshot from 2023-11-12 20-57-41](https://github.com/cvlab-stonybrook/DewarpNet/assets/1169926/820f8eef-609a-4587-a6cd-a8609b13855e)

Questions:
- I know the dataset is not public (but only available on demand), but I wonder if, from a quick look, you consider the current limitations to be caused by dataset's limitation or rather the chosen NN?
- In the first case, would you suggest retraining on an enriched dataset?
- If yes, do you anticipate that a limited amount of (manually) cropped (containing staples/partial corner occlusion), used with their original counterpart, for training, would significantly improve the overall detection?

**Comment by sagniklp** [comment]
Yes it will improve, please refer to our follow up work [PaperEdge](https://github.com/cvlab-stonybrook/PaperEdge.git) for such unwarping tasks.
