### ISSUE TITLE
Pre-trained models not available

### ISSUE THREAD

**Issue by StaelTchinda** [cvlab-stonybrook/DewarpNet#62]
Hi,

first thank you for this work.

The [link to the google drive](https://drive.google.com/file/d/1hJKCb4eF1AJih_dhZOJSF5VR-ZtRNaap/view?usp=sharing) from [eval/models](https://github.com/cvlab-stonybrook/DewarpNet/tree/master/eval/models) of the pre-trained models is unfortunately not available anymore. Could you please update it ?

Thank you !

**Comment by sagniklp** [comment]
It's in the main [readme](https://github.com/cvlab-stonybrook/DewarpNet?tab=readme-ov-file#models)
